### ISSUE TITLE
Crashes on macOS

### ISSUE THREAD

**Issue by ghost** [yug95/node-mysql#2]
Installed all dependencies.
when I am going to run it, it is crashed.

server connected to port 9890

```
/Volumes/Work/node-mysql/node_modules/mysql/lib/protocol/Parser.js:80
throw err; // Rethrow non-MySQL errors
^
TypeError: Cannot read property 'release' of undefined

```

**Comment by yug95** [comment]
Need to setup MySQL database also. With the same name please check database.js file

**Comment by yug95** [comment]
is it solved or still you are getting?

**Comment by Aurelyn10** [comment]
still getting error.
